# Generated by Django 5.2 on 2025-04-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
